import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en" className='app-html'>
      <Head>
        <title>Reliable Property</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/reset.css" />
      </Head>
      <body className='app-body'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
